layout_spectrum: 0.4810018096637386
typography_spectrum: 0.33509108034294505
color:
  brandStrength: 0.9475814730307953
  lightness: 0.12253363418402058
  saturation: 0.7319741939463754
  rhythmicContrast: 0.132766384125346
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
github: true
author:
  name: Mark Vange
  email: mvange@tokeniq.io
  url: 'https://www.linkedin.com/in/markvange/'
name: tokeniq.io
url: 'http://tokeniq.io/'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
title: Token IQ
content: []
description: Making Smarter Tokens
purpose:
  - type: contact
    url: 'mailto:mvange@tokeniq.io'
    label: Get in touch
logo: null
