layout_spectrum: 0.4810018096637386
typography_spectrum: 0.33509108034294505
color:
  brandStrength: 0.9475814730307953
  lightness: 0.12253363418402058
  saturation: 0.7319741939463754
  rhythmicContrast: 0.132766384125346
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
github: true
author:
  name: Mark Vange
  email: mvange@tokeniq.io
  url: 'https://www.linkedin.com/in/markvange/'
name: tokeniq.io
url: 'http://tokeniq.io/'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
title: Token IQ
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/57a217ae-fd9e-4345-8509-251e781fd903.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/57a217ae-fd9e-4345-8509-251e781fd903.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/6c978386-471f-4218-a598-429ead5fd471.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/6c978386-471f-4218-a598-429ead5fd471.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  The ERC-20 token and similar technologies are not capable of providing a truly
  compliant solution to the tokenization of securities, nor even to delivering a
  fully compliant ICO.  A simple example is that in the cryptocurrency world
  loss of access to a wallet renders the token-holder incapable of capitalizing
  on gains while in the real world the loss of a share certificate in no way
  undermines a shareholder’s claim to their rights.  Our Solution: Create a
  scalable technology solutions that allows us to tokenize securities, be they
  ICOs or traditional security offerings.  Specifically, we address the key
  areas of: token Monetization, AML and KYC compliance, ongoing-compliance and
  market-making. Among the numerous capabilities that are missing from today’s
  crypto currencies are Futures, Vesting, Options (American and European),
  Indexes, Swaps, Forward Contracts, Lost token handling, Inheritance,
  Custodianship, Court Judgement enforcement.  While some have talked about
  approaching a few of these capabilities through the deployment of an exchange
  mechanism, we believe that a better way is to build these directly into the
  token.  The Token IQ solution makes all these capabilities available to
  tokenized securities, be they ICOs today or conventional securities in the
  future.  Our immediate business opportunity is each and every company that has
  issued a SAFT agreement or is interested in fully legal, compliant and mature
  Tokenization that is available to all investors and is "on-side" with SEC and
  other regulators.
purpose:
  - type: contact
    url: 'mailto:mvange@tokeniq.io'
    label: Get in touch
logo: null
